# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/owgrant/hdd1/dev/qgis/cadaster_import/cadaster_import_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CadasterImportDockWidgetBase(object):
    def setupUi(self, CadasterImportDockWidgetBase):
        CadasterImportDockWidgetBase.setObjectName("CadasterImportDockWidgetBase")
        CadasterImportDockWidgetBase.resize(391, 831)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.importButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.importButton.setEnabled(False)
        self.importButton.setAutoFillBackground(False)
        self.importButton.setObjectName("importButton")
        self.gridLayout.addWidget(self.importButton, 4, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.dockWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.analizeButton = QtWidgets.QPushButton(self.frame)
        self.analizeButton.setEnabled(False)
        self.analizeButton.setGeometry(QtCore.QRect(240, 90, 121, 25))
        self.analizeButton.setObjectName("analizeButton")
        self.info = QtWidgets.QTextEdit(self.frame)
        self.info.setGeometry(QtCore.QRect(10, 130, 351, 571))
        self.info.setReadOnly(True)
        self.info.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info.setObjectName("info")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 351, 50))
        self.layoutWidget.setObjectName("layoutWidget")
        self.selectFileLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.selectFileLayout.setContentsMargins(0, 0, 0, 0)
        self.selectFileLayout.setObjectName("selectFileLayout")
        self.selectDirectoryLabel = QtWidgets.QLabel(self.layoutWidget)
        self.selectDirectoryLabel.setObjectName("selectDirectoryLabel")
        self.selectFileLayout.addWidget(self.selectDirectoryLabel)
        self.selectDirectoryWidget = gui.QgsFileWidget(self.layoutWidget)
        self.selectDirectoryWidget.setFilter("")
        self.selectDirectoryWidget.setStorageMode(gui.QgsFileWidget.GetDirectory)
        self.selectDirectoryWidget.setOptions(QtWidgets.QFileDialog.ShowDirsOnly)
        self.selectDirectoryWidget.setObjectName("selectDirectoryWidget")
        self.selectFileLayout.addWidget(self.selectDirectoryWidget)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 2)
        self.progressBarLabel = QtWidgets.QLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBarLabel.sizePolicy().hasHeightForWidth())
        self.progressBarLabel.setSizePolicy(sizePolicy)
        self.progressBarLabel.setObjectName("progressBarLabel")
        self.gridLayout.addWidget(self.progressBarLabel, 2, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.dockWidgetContents)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.dockWidgetContents)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Help)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 1)
        CadasterImportDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(CadasterImportDockWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(CadasterImportDockWidgetBase)

    def retranslateUi(self, CadasterImportDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        CadasterImportDockWidgetBase.setWindowTitle(_translate("CadasterImportDockWidgetBase", "Импорт XML файлов ЕГРН"))
        self.importButton.setText(_translate("CadasterImportDockWidgetBase", "Импорт"))
        self.importButton.setShortcut(_translate("CadasterImportDockWidgetBase", "Return"))
        self.analizeButton.setText(_translate("CadasterImportDockWidgetBase", "Анализ файлов"))
        self.selectDirectoryLabel.setText(_translate("CadasterImportDockWidgetBase", "Выберите директорию"))
        self.progressBarLabel.setText(_translate("CadasterImportDockWidgetBase", "TextLabel"))
from qgis import gui
